import { Inspection, VehicleInfo } from './inspection-types';
import { MOCK_PHOTOS_GALLERY, MOCK_TEMPLATES } from './mock-inspection-data';

export interface AccessLogEntry {
  id: string;
  userName: string;
  userEmail: string;
  userRole: 'Proprietário' | 'Administrador' | 'Operador de Pátio' | 'Supervisor';
  branch: string;
  device: string;
  browser: string;
  ipAddress: string;
  location: string;
  loginTime: string;
  lastActivity: string;
  status: 'ONLINE' | 'OFFLINE' | 'EXPIRED';
  isCurrentSession?: boolean;
}

export interface InspectionHistoryItem extends Inspection {
  branchName: string;
  inspectionDuration: string;
  damageCount: number;
  photosCount: number;
  classification: 'APROVADO' | 'COM_AVARIA' | 'REPROVADO' | 'PENDENTE';
}

export const MOCK_ACCESS_LOGS: AccessLogEntry[] = [
  {
    id: 'log-1',
    userName: 'Carlos Mendes',
    userEmail: 'carlos.mendes@locafrotas.com.br',
    userRole: 'Proprietário',
    branch: 'Sede Administrativa - SP',
    device: 'MacBook Pro 16" (macOS Sonoma)',
    browser: 'Chrome 128.0',
    ipAddress: '187.54.120.33',
    location: 'São Paulo, SP - Brasil',
    loginTime: 'Hoje às 14:15',
    lastActivity: 'Há 2 minutos',
    status: 'ONLINE',
    isCurrentSession: true,
  },
  {
    id: 'log-2',
    userName: 'Juliana Paes Silva',
    userEmail: 'juliana.silva@locafrotas.com.br',
    userRole: 'Operador de Pátio',
    branch: 'Pátio Congonhas - SP',
    device: 'Apple iPhone 15 Pro (iOS 18)',
    browser: 'Safari Mobile 18.0',
    ipAddress: '177.132.88.14',
    location: 'São Paulo (Zona Sul), SP',
    loginTime: 'Hoje às 09:30',
    lastActivity: 'Há 8 minutos',
    status: 'ONLINE',
  },
  {
    id: 'log-3',
    userName: 'Marcos Vinicius Santos',
    userEmail: 'marcos.santos@locafrotas.com.br',
    userRole: 'Operador de Pátio',
    branch: 'Filial Campinas - SP',
    device: 'Samsung Galaxy Tab S9 (Android 14)',
    browser: 'SURVEY Mobile App v2.4',
    ipAddress: '201.86.14.90',
    location: 'Campinas, SP',
    loginTime: 'Hoje às 08:45',
    lastActivity: 'Há 15 minutos',
    status: 'ONLINE',
  },
  {
    id: 'log-4',
    userName: 'Marcos Silveira',
    userEmail: 'marcos.silveira@locafrotas.com.br',
    userRole: 'Operador de Pátio',
    branch: 'Pátio Central - SP',
    device: 'Motorola Edge 40 (Android 14)',
    browser: 'Chrome Mobile 128',
    ipAddress: '189.40.71.105',
    location: 'São Paulo (Centro), SP',
    loginTime: 'Ontem às 17:50',
    lastActivity: 'Ontem às 18:30',
    status: 'OFFLINE',
  },
  {
    id: 'log-5',
    userName: 'Roberto Antunes',
    userEmail: 'roberto.frota@locafrotas.com.br',
    userRole: 'Supervisor',
    branch: 'Pátio Congonhas - SP',
    device: 'Dell Latitude 5420 (Windows 11)',
    browser: 'Microsoft Edge 127',
    ipAddress: '186.204.99.12',
    location: 'São Paulo, SP',
    loginTime: 'Ontem às 15:20',
    lastActivity: 'Ontem às 17:10',
    status: 'OFFLINE',
  },
  {
    id: 'log-6',
    userName: 'Aline Ferreira',
    userEmail: 'aline.ferreira@locafrotas.com.br',
    userRole: 'Operador de Pátio',
    branch: 'Pátio Central - SP',
    device: 'Xiaomi Redmi Note 13 (Android 13)',
    browser: 'Chrome Mobile',
    ipAddress: '179.184.22.41',
    location: 'Guarulhos, SP',
    loginTime: '08/09/2026 às 11:10',
    lastActivity: '08/09/2026 às 12:00',
    status: 'EXPIRED',
  },
];

export const MOCK_HISTORICAL_INSPECTIONS: InspectionHistoryItem[] = [
  {
    id: 'insp_78942',
    vehicle: {
      plate: 'BRA2E19',
      model: 'Civic EXL 2.0 Flex Aut.',
      brand: 'Honda',
      year: 2022,
      color: 'Prata Platinum',
      chassis: '93HFC2630NZ109842',
      mileage: 38450,
      customerName: 'Localiza Gestão de Frotas',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-completa',
    templateName: 'Vistoria Completa',
    status: 'COMPLETED',
    startedAt: '10/09/2026 às 14:30',
    completedAt: '10/09/2026 às 14:48',
    operatorName: 'Marcos Silveira (Operador Sênior)',
    branchName: 'Pátio Central - SP',
    inspectionDuration: '18 min',
    damageCount: 1,
    photosCount: 6,
    classification: 'COM_AVARIA',
    stepStatuses: {
      'step-1': 'COMPLETED',
      'step-2': 'COMPLETED',
      'step-3': 'COMPLETED',
      'step-4': 'COMPLETED',
      'step-5': 'COMPLETED',
      'step-6': 'COMPLETED',
      'step-7': 'COMPLETED',
    },
    responses: {
      'step-1': {
        stepId: 'step-1',
        value: 'Novos / Pouco uso',
        notes: 'Pneus dianteiros e traseiros originais Michelin, banda de rodagem com mais de 6mm.',
        photos: [MOCK_PHOTOS_GALLERY.pneus],
        completedAt: '14:34',
      },
      'step-2': {
        stepId: 'step-2',
        value: true,
        notes: 'Lâmpadas de LED funcionando perfeitamente, sem trincas nas lentes.',
        photos: [MOCK_PHOTOS_GALLERY.farois],
        completedAt: '14:36',
      },
      'step-3': {
        stepId: 'step-3',
        value: ['Riscos superficiais'],
        notes: 'Risco superficial de aproximadamente 5cm no para-choque traseiro direito.',
        photos: [MOCK_PHOTOS_GALLERY.lataria],
      },
    },
  },
  {
    id: 'insp_78943',
    vehicle: {
      plate: 'RTL4B12',
      model: 'Corolla Cross XRE 2.0',
      brand: 'Toyota',
      year: 2024,
      color: 'Branco Polar',
      chassis: '9BRBL42B5RP098124',
      mileage: 14200,
      customerName: 'Movida Locação Corporativa',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-rapida',
    templateName: 'Vistoria Rápida',
    status: 'COMPLETED',
    startedAt: '10/09/2026 às 11:20',
    completedAt: '10/09/2026 às 11:27',
    operatorName: 'Juliana Paes Silva',
    branchName: 'Pátio Congonhas - SP',
    inspectionDuration: '7 min',
    damageCount: 0,
    photosCount: 4,
    classification: 'APROVADO',
    stepStatuses: {
      'step-r-1': 'COMPLETED',
      'step-r-2': 'COMPLETED',
      'step-r-3': 'COMPLETED',
      'step-r-4': 'COMPLETED',
    },
    responses: {
      'step-r-1': {
        stepId: 'step-r-1',
        value: '14.200 km - Tanque Cheio',
        notes: 'Painel 100% sem alertas de injeção ou freio.',
        photos: [],
      },
      'step-r-2': {
        stepId: 'step-r-2',
        value: true,
        notes: 'Lataria e pintura impecáveis, sem nenhum risco aparente.',
        photos: [],
      },
    },
  },
  {
    id: 'insp_78944',
    vehicle: {
      plate: 'GHX9J88',
      model: 'Compass Longitude 1.3 Turbo',
      brand: 'Jeep',
      year: 2023,
      color: 'Cinza Granite',
      chassis: '988FB24K0P781923',
      mileage: 46100,
      customerName: 'Unidas Frotas Terceirizadas',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-oficina',
    templateName: 'Checklist de Oficina & Manutenção',
    status: 'COMPLETED',
    startedAt: '10/09/2026 às 09:10',
    completedAt: '10/09/2026 às 09:32',
    operatorName: 'Marcos Vinicius Santos',
    branchName: 'Filial Campinas - SP',
    inspectionDuration: '22 min',
    damageCount: 2,
    photosCount: 8,
    classification: 'COM_AVARIA',
    stepStatuses: {
      'step-of-1': 'COMPLETED',
      'step-of-2': 'COMPLETED',
      'step-of-3': 'COMPLETED',
      'step-of-4': 'COMPLETED',
    },
    responses: {
      'step-of-4': {
        stepId: 'step-of-4',
        value: ['Amassado na porta', 'Risco no para-choque'],
        notes: 'Pequena mossa na porta dianteira esquerda e ralado no para-choque frontal.',
        photos: [],
      },
    },
  },
  {
    id: 'insp_78945',
    vehicle: {
      plate: 'QWP3C77',
      model: 'HB20 Comfort 1.0 Flex',
      brand: 'Hyundai',
      year: 2024,
      color: 'Preto Onix',
      chassis: '9BHBH41BBPP230198',
      mileage: 9800,
      customerName: 'Kovi Frotas por Assinatura',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-rapida',
    templateName: 'Vistoria Rápida',
    status: 'COMPLETED',
    startedAt: '09/09/2026 às 16:45',
    completedAt: '09/09/2026 às 16:51',
    operatorName: 'Juliana Paes Silva',
    branchName: 'Pátio Congonhas - SP',
    inspectionDuration: '6 min',
    damageCount: 0,
    photosCount: 3,
    classification: 'APROVADO',
    stepStatuses: {
      'step-r-1': 'COMPLETED',
      'step-r-2': 'COMPLETED',
      'step-r-3': 'COMPLETED',
    },
    responses: {},
  },
  {
    id: 'insp_78946',
    vehicle: {
      plate: 'FJR8K21',
      model: 'Onix Plus Premier 1.0 Turbo',
      brand: 'Chevrolet',
      year: 2023,
      color: 'Azul Seeker',
      chassis: '9BGAF48W0PG129031',
      mileage: 31200,
      customerName: 'Piratininga Logística',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-completa',
    templateName: 'Vistoria Completa',
    status: 'COMPLETED',
    startedAt: '09/09/2026 às 13:10',
    completedAt: '09/09/2026 às 13:25',
    operatorName: 'Marcos Silveira (Operador Sênior)',
    branchName: 'Pátio Central - SP',
    inspectionDuration: '15 min',
    damageCount: 0,
    photosCount: 5,
    classification: 'APROVADO',
    stepStatuses: {
      'step-1': 'COMPLETED',
      'step-2': 'COMPLETED',
    },
    responses: {},
  },
  {
    id: 'insp_78947',
    vehicle: {
      plate: 'SXY1A45',
      model: 'T-Cross Highline 250 TSI',
      brand: 'Volkswagen',
      year: 2024,
      color: 'Cinza Platinum',
      chassis: '9BWDB4BF1RP102834',
      mileage: 8200,
      customerName: 'TransVale Transporte Executivo',
      companyName: 'Locafrotas Brasil Ltda.',
    },
    templateId: 'tpl-completa',
    templateName: 'Vistoria Completa',
    status: 'IN_PROGRESS',
    startedAt: 'Hoje às 15:10',
    operatorName: 'Marcos Vinicius Santos',
    branchName: 'Filial Campinas - SP',
    inspectionDuration: 'Em execução...',
    damageCount: 0,
    photosCount: 2,
    classification: 'PENDENTE',
    stepStatuses: {
      'step-1': 'COMPLETED',
      'step-2': 'IN_PROGRESS',
      'step-3': 'PENDING',
    },
    responses: {},
  },
];
